name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Set up uv
      uses: astral-sh/setup-uv@v1

    - name: Create virtual environment
      run: uv venv -p 3.13

    - name: Install dependencies
      run: uv pip install .[dev]

    - name: Run ruff format check
      run: ruff format --check .

    - name: Run pytest
      run: pytest
