name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.3"
        cache: true

    - name: Install dependencies
      run: uv sync --frozen --all-extras --dev

    - name: Run pytest
      run: uv run pytest -v

    - name: Run ruff format check
      run: uv run ruff format --check .